version: '3.3'
services:
    actual-http-api:
        container_name: actualhttpapi
        volumes:
            - './data:/data:rw'
        ports:
            - '5007:5007'
        environment:
            - 'ACTUAL_SERVER_URL=http://localhost:5006/'
            - 'ACTUAL_SERVER_PASSWORD=my-actual-server-password'
            - 'API_KEY=my-strong-api-key'
        restart: on-failure
        image: jhonderson/actual-http-api:latest